chore: Update Gatsby quickstart guide
clerkinc/clerk-docs pull request #156
Opened 2023-08-06 13:18 UTC by LekoArts

Hi!

Here are some improvements to the Gatsby quickstart guide, most notably correcting that its config file is `gatsby-config.ts` and not `gatsby.config.ts` :)

2023-08-07 03:01 UTC, jescalan approved these changes
🤩

2023-08-07 14:32 UTC, alexisintech requested changes
Just some grammar/editorial adjustments to make sure the content is polished 😄

2023-08-07 14:32 UTC, alexisintech commented on src/pages/quickstarts/full-stack/gatsby.mdx
>  Clerk offers Control Components that allow you to protect your pages, below is a simple example using Clerk's hosted components and the `<SignedIn/>` and `<SignedOut/>` control components.
```suggestion
Clerk offers Control Components that allow you to protect your pages. Below is a simple example using Clerk's hosted components and the `<SignedIn />` and `<SignedOut />` control components.
```

2023-08-07 14:32 UTC, alexisintech commented on src/pages/quickstarts/full-stack/gatsby.mdx
> +Below is an example of your `.env.development` file. To get the respective keys go to the API Keys page in the Clerk dashboard.
```suggestion
Below is an example of your `.env.development` file. To get the respective keys, go to the API Keys page in the Clerk dashboard.
```

2023-08-07 14:32 UTC, alexisintech commented on src/pages/quickstarts/full-stack/gatsby.mdx
> +To use Clerk you will need to update your `gatsby-config.ts` to resolve `gatsby-plugin-clerk` and load from `.env` files.
```suggestion
To use Clerk, you will need to update your `gatsby-config.ts` in order to resolve `gatsby-plugin-clerk` and load from `.env` files.
```

2023-08-08 14:46 UTC, alexisintech approved these changes
😸💖

2023-08-10 19:23 UTC, BRKalow commented
Updated and merged in https://github.com/clerkinc/clerk-docs/pull/167, thank you for your contribution!

2023-08-10 19:23 UTC, closed without merging