Shehz/account portal
clerkinc/clerk-docs pull request #218
Opened 2023-08-24 17:04 UTC by msakbar

Updates Made:
1. Added all Account Portal Pages (Overview, Getting Started, Custom Redirects, UserProfile/OrgProfile & Disable)
2. Added the contextual component references under Account Portal 
3. Added afterSignInURL, afterSignUpURL, redirectURL props to appropriate components
4. Added '"RedirectToOrganizationProfile "' page
5. Added '"RedirectToCreateOrganization "' page

2023-08-24 17:56 UTC, perkinsjr requested changes
Just some changes to wording and some missed styling

2023-08-24 17:56 UTC, perkinsjr commented on docs/account-portal/overview.mdx
> +You can access these links via the 'pages' tab under Account Portal in your Clerk dashboard.
Add links to dashboard here.

2023-08-24 17:56 UTC, perkinsjr commented on docs/account-portal/overview.mdx
> +The Account Portal provides all pages out of the box hosted on Clerk servers for you and requires minimal setup to get started, if you’re looking for the fastest way to get your application up and ru
This phrasing is very confusing. "provides all pages out of the box" what pages?

2023-08-24 17:56 UTC, perkinsjr commented on docs/account-portal/getting-started.mdx
> +## React
This should be outside the step

2023-08-29 15:26 UTC, alexisintech submitted a review, later dismissed

2023-08-29 15:26 UTC, alexisintech commented on docs/account-portal/custom-redirects.mdx
> +</Tabs>
Let's use code block tabs here instead! This is my mistake - I had a different direction and was going to put some content into the Next.js tab but we went a different direction.

2023-09-07 20:50 UTC, alexisintech requested changes
Just really nit picky things because I'm crazy, but with the new OG Images about to ship, we want to remove MDX syntax from front matter - its a ticket that I am going to get to after the OG Images ship.

2023-09-07 20:50 UTC, alexisintech commented on docs/account-portal/direct-links.mdx
> +Set your fallback host under **Paths** in the Clerk Dashboard.
```suggestion
Set your fallback host under [Paths](https://dashboard.clerk.com/last-active?path=paths) in the Clerk Dashboard. 
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/control/redirect-to-createorganization.mdx
> +description: The `<RedirectToCreateOrganization />` component will navigate to the user profile URL which has been configured in your application instance. The behavior will be just like a server-sid
Remove MDX syntax from frontmatter

```suggestion
description: The <RedirectToCreateOrganization /> component will navigate to the user profile URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect, and will override the current location in the history stack.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/control/redirect-to-organizationprofile.mdx
> +description: The `<RedirectToOrganizationProfile />` component will navigate to the organization profile URL which has been configured in your application instance. The behavior will be just like a s
Remove MDX syntax from frontmatter

```suggestion
description: The <RedirectToOrganizationProfile /> component will navigate to the organization profile URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect, and will override the current location in the history stack.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/control/redirect-to-signin.mdx
>  description: The `<RedirectToSignIn />` component will navigate to the sign in URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect,
Remove MDX syntax from frontmatter

```suggestion
description: The <RedirectToSignIn /> component will navigate to the sign in URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect, and will override the current location in the history stack.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/control/redirect-to-signup.mdx
>  description: The `<RedirectToSignUp />` component will navigate to the sign up URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect,
Remove MDX syntax from frontmatter

```suggestion
description: The <RedirectToSignUp /> component will navigate to the sign up URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect, and will override the current location in the history stack.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/control/redirect-to-userprofile.mdx
>  description: The `<RedirectToUserProfile />` component will navigate to the user profile URL which has been configured in your application instance. The behavior will be just like a server-side (3xx)
Remove MDX syntax from frontmatter

```suggestion
description: The <RedirectToUserProfile /> component will navigate to the user profile URL which has been configured in your application instance. The behavior will be just like a server-side (3xx) redirect, and will override the current location in the history stack.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/unstyled/sign-in-button.mdx
>  description: The `<SignInButton />` component is a button that links to the sign-in page or displays the sign-in modal.
Remove MDX syntax from frontmatter

```suggestion
description: The <SignInButton /> component is a button that links to the sign-in page or displays the sign-in modal.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/components/unstyled/sign-up-button.mdx
>  description: The `<SignUpButton />` component is a button that links to the sign-up page or displays the sign-up modal.
Remove MDX syntax from frontmatter

```suggestion
description: The <SignUpButton /> component is a button that links to the sign-up page or displays the sign-up modal.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/account-portal/custom-redirects.mdx
> +description:  Customize where your users are redirected to after they sign-in or sign-up.
```suggestion
description:  Customize where your users are redirected to after they sign in or sign up.
```

2023-09-07 20:50 UTC, alexisintech commented on docs/account-portal/direct-links.mdx
> +description: Learn how to share direct links to your Account Portal pages, and how to set up fallback redirects
```suggestion
description: Learn how to share direct links to your Account Portal pages, and how to set up fallback redirects.
```

2023-09-08 12:55 UTC, alexisintech approved these changes
😸💖

2023-09-08 13:23 UTC, merged