Updated information and code for App Router
clerkinc/clerk-docs pull request #266
Opened 2023-09-06 20:56 UTC by royanger

- Clarified api/ for Page Router and app/ for App Router
- Updated App Router example to remove unused imports, improve flow

2023-09-06 21:21 UTC, alexisintech requested changes

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +If you're using Next.js with Page Router, you can create a webhook endpoint in the `pages/api` directory.
```suggestion
If you're using Next.js with Pages Router, you can create a webhook endpoint in the `pages/api` directory.
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // you can find this in the Clerk Dashboard -> Webhooks -> choose the webhook
```suggestion
  // You can find this in the Clerk Dashboard -> Webhooks -> choose the webhook
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // get the headers
```suggestion
  // Get the headers
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // if there are no headers, error out
```suggestion
  // If there are no headers, error out
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // get the body
```suggestion
  // Get the body
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // create a new SVIX instance with your secret.
```suggestion
  // Create a new SVIX instance with your secret.
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // verify the payload with the headers
```suggestion
  // Verify the payload with the headers
```

2023-09-06 21:21 UTC, alexisintech commented on docs/users/sync-data.mdx
> +  // get the id and type
```suggestion
  // Get the ID and type
```

2023-09-06 21:43 UTC, alexisintech approved these changes
Last thing is that I would capitalize the comments for the App Router example as well, for consistency sake.
I'll go ahead and approve so you can make those changes and be all set 😸💖

2023-09-06 23:52 UTC, royanger commented
Pretty sure you meant 'Pages Router example as well' but wanted to be clear on that before merging @alexisintech? Thanks for approving.

2023-09-06 23:59 UTC, alexisintech commented
> Pretty sure you meant 'Pages Router example as well' but wanted to be clear on that before merging @alexisintech? Thanks for approving.

hmm, looking at the preview, the comments for the pages router example are capitalized. and the app router ones are not.

Uploading Screen Recording 2023-09-06 at 19.58.58.mov…

2023-09-07 00:12 UTC, royanger commented
The deploy-preview didn't build the changes. Looking at the file in the most recent commit and I see all comments for all code examples capitalized. I can run the deploy-preview again if needed. Let me know.

2023-09-07 00:23 UTC, alexisintech commented
> The deploy-preview didn't build the changes. Looking at the file in the most recent commit and I see all comments for all code examples capitalized. I can run the deploy-preview again if needed. Let me know.

oh then it's all good! I approved so you could use your better judgement, so go ahead and merge away if you feel ready 😄 it all looks good to me!

2023-09-07 01:05 UTC, merged