migrate page from sanity to mdx
clerkinc/clerk-docs pull request #319
Opened 2023-09-20 17:35 UTC by alexisintech

/docs/custom-flows/multi-session-applications

This PR

- migrates this page from Sanity to MDX
- adds links to references
- adds image and optimized using Squoosh

Acknowledging that these pages probably need work, and need their code examples updated - but for the scope of "Sanity to MDX Migration", this can be revisited at a later time, with better resources.

For reference, this is what the page looked like before this PR:

https://github.com/clerkinc/clerk-docs/assets/98043211/65b5970f-6868-4f6e-8fb7-d66270925c2d

2023-09-21 19:32 UTC, BrandonRomano commented
@alexisintech, one small ergonomic thing I recommend you can include for reviewers on these PRs:

Preview Links:
- [🔍 Preview of updates](https://docs-preview-319.clerkpreview.com/docs/custom-flows/multi-session-applications)
- [🔍 Old page](https://clerk.com/docs/custom-flows/multi-session-applications)

This will make it slightly quicker to review these PRs which I think will make it ever so slightly easier to get timely PRs!

2023-09-21 19:33 UTC, BrandonRomano requested changes
![CleanShot 2023-09-21 at 12 33 02@2x](https://github.com/clerkinc/clerk-docs/assets/2105067/f1c4d9f2-15ad-4d41-bc0c-03650503ee93)

An image is not loading for me on the page.  Tried refreshing a few times to no avail.

2023-09-21 21:27 UTC, alexisintech commented
> ![CleanShot 2023-09-21 at 12 33 02@2x](https://user-images.githubusercontent.com/2105067/269734479-f1c4d9f2-15ad-4d41-bc0c-03650503ee93.png)
> 
> An image is not loading for me on the page. Tried refreshing a few times to no avail.

ahh, because the image was added in other pr!! that pr is now merged, so it should now be ok

2023-09-22 02:08 UTC, jescalan reviewed
Just one small image width thing

2023-09-22 02:08 UTC, jescalan commented on docs/custom-flows/multi-session-applications.mdx
> +  width={880}
Image load is now fixed but it looked way too wide to me - this felt a bit more reasonable

```suggestion
  width={400}
```

2023-09-22 16:47 UTC, BrandonRomano approved these changes
LGTM

2023-09-22 17:02 UTC, merged