Fix broken link on testing overview
clerkinc/clerk-docs pull request #360
Opened 2023-09-28 18:48 UTC by johnjensenish

URL https://clerk.com/docs/testing/e2e-testing doesn't exist

Also cleaned up some phrasing IMO

2023-09-29 13:58 UTC, alexisintech requested changes

2023-09-29 13:58 UTC, alexisintech commented on docs/testing/overview.mdx
> +Testing is an important part of every application. Clerk has built some helpers to make testing your application with Clerk easier, with more on the way. End-to-end (E2E) tests should be possible in
```suggestion
Testing is an important part of every application. Clerk has built some helpers to make testing your application with Clerk easier, with more on the way. End-to-end (E2E) tests should be possible in any framework. However, each framework may require a slightly different setup. If you're having trouble getting testing to work properly, [send us a message](https://clerk.com/support) and we'll be able to help.
```

2023-09-29 20:41 UTC, johnjensenish commented
@alexisintech Your suggested change has been committed :)

2023-10-02 20:45 UTC, alexisintech approved these changes
Thank you for these catches!! 😸💖

2023-10-02 20:45 UTC, merged