clean up /components
clerkinc/clerk-docs pull request #369
Opened 2023-09-29 17:05 UTC by alexisintech

- removes unnecessary imports
- migrates `<Table />` components to markdown tables
- adds links to references where necessary

2023-10-03 16:24 UTC, BRKalow commented on docs/components/authentication/sign-in.mdx
> -| `path` | `string` | The path where the component is mounted on when path-based routing is used e.g. /sign-up. Note: If you are using Environment Variables for Next.js or Remix to specify your route
Oops it looks like this note was on the wrong prop. We should keep the note but move it to the `routing` row.

2023-10-03 16:26 UTC, BRKalow commented on docs/components/authentication/sign-up.mdx
> -| `routing` | `string` | The routing strategy for your pages.<br />Supported values are: <ul><li>hash (default): Hash-based routing.</li> <li>path: Path-based routing.</li> <li>virtual: Virtual-based
This note should stay 👍

2023-10-03 16:46 UTC, BRKalow requested changes
Some very minor formatting things, but overall looks great!

2023-10-03 16:46 UTC, BRKalow commented on docs/components/clerk-provider.mdx
> +| `publishableKey` | `string \| undefined` | The publishable key from your Clerk Dashboard, used to connect to Clerk |
```suggestion
| `publishableKey` | `string \| undefined` | The publishable key from your Clerk Dashboard, used to connect to Clerk. |

```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/customization/layout.mdx
> +| `termsPageUrl` | `string` | The URL to your terms page |
```suggestion
| `helpPageUrl` | `string` | The URL to your help page. |
| `logoImageUrl` | `string` | The URL to your logo image. |
| `logoPlacement` | `'inside' \| 'outside'` | The placement of your logo.  |
| `privacyPageUrl` | `string` | The URL to your privacy page. |
| `showOptionalFields` | `boolean` | Whether to show optional fields on sign up. |
| `socialButtonsPlacement` | `'bottom' \| 'top'` | The placement of your social buttons. |
| `socialButtonsVariant` | `'blockButton' \| 'textButton' \| 'auto'` | The variant of your social buttons. |
| `termsPageUrl` | `string` | The URL to your terms page. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/customization/variables.mdx
> +| `spacingUnit` | `string` | The spacing unit used throughout the components. By default, this is set to 1rem. |
```suggestion
| `colorPrimary` | `string` | The primary color used throughout the components. |
| `colorDanger` | `string` | The color used for error states. |
| `colorSuccess` | `string` | The color used for success states. |
| `colorWarning` | `string` | The color used for warning states. |
| `colorAlphaShade` | `string` | The color that will be used for all to generate the alpha shades the components use. This option applies to borders, backgrounds for hovered elements, hovered dropdown options. |
| `colorTextOnPrimaryBackground` | `string` | The color used for text on the primary background. |
| `colorTextSecondary` | `string` | The color used for secondary text. |
| `colorBackground` | `string` | The background color for the card container. |
| `colorInputText` | `string` | The color used for text in input fields. |
| `colorInputBackground` | `string` | The background color used for input fields. |
| `fontFamily` | `string` | The font family used throughout the components. By default, it is inherited. |
| `fontFamilyButtons` | `string` | The font family used for buttons. By default, it is inherited. |
| `fontSize` | `string` | The font size used throughout the components. By default, this is set to 1rem. |
| `fontSmoothing` | `'auto' \| 'antialiased' \| 'never'` | The font smoothing used throughout the components. By default, this is set to auto. |
| `fontWeight` | `{normal: number, medium: number, bold: number}` | The font weight used throughout the components. By default, this is set to `{normal: 400, medium: 500, bold: 600}`. |
| `borderRadius` | `string` | The border radius used throughout the components. By default, this is set to `0.375rem`. |
| `spacingUnit` | `string` | The spacing unit used throughout the components. By default, this is set to `1rem`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/organization/organization-list.mdx
> +| `hidePersonal` | `boolean` | By default, users can switch between organization and their personal account. This option controls whether `<OrganizationList />` will include the user's personal accou
```suggestion
| `hidePersonal` | `boolean` | By default, users can switch between organization and their personal account. This option controls whether `<OrganizationList />` will include the user's personal account in the organization list. Setting this to `false` will hide the personal account entry, and users will only be able to switch between organizations. <br />Defaults to `false`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/organization/organization-switcher.mdx
> +| `createOrganizationMode` | `'modal' \| 'navigation'` | Controls whether clicking the "Create organization" button will cause the [`<CreateOrganization />`][createorg-ref] component to open as a mod
```suggestion
| `createOrganizationMode` | `'modal' \| 'navigation'` | Controls whether clicking the "Create organization" button will cause the [`<CreateOrganization />`][createorg-ref] component to open as a modal, or if the browser will navigate to the `createOrganizationUrl` where [`<CreateOrganization />`][createorg-ref] is mounted as a page.<br />Defaults to: `"modal"`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/organization/organization-switcher.mdx
> +| `organizationProfileMode` | `'modal' \| 'navigation'` | Controls whether clicking the "Manage organization" button will cause the [`<OrganizationProfile />`][orgprofile-ref] component to open as a
```suggestion
| `organizationProfileMode` | `'modal' \| 'navigation'` | Controls whether clicking the "Manage organization" button will cause the [`<OrganizationProfile />`][orgprofile-ref] component to open as a modal, or if the browser will navigate to the `organizationProfileUrl` where [`<OrganizationProfile />`][orgprofile-ref] is mounted as a page.<br />Defaults to: `"modal"`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/organization/organization-switcher.mdx
> +| `hidePersonal` | `boolean` | By default, users can switch between organization and their personal account. This option controls whether [`<OrganizationSwitcher />`][orgswitcher-ref] will include th
```suggestion
| `hidePersonal` | `boolean` | By default, users can switch between organization and their personal account. This option controls whether [`<OrganizationSwitcher />`][orgswitcher-ref] will include the user's personal account in the organization list. Setting this to `false` will hide the personal account entry, and users will only be able to switch between organizations.<br />Defaults to: `true`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/user/user-button.mdx
> +| `userProfileMode` | <code>"modal" \| "navigation"</code> | Controls whether clicking the "Manage your account" button will cause the [`<UserProfile />`][userprofile-ref] component to open as a moda
```suggestion
| `userProfileMode` | <code>"modal" \| "navigation"</code> | Controls whether clicking the "Manage your account" button will cause the [`<UserProfile />`][userprofile-ref] component to open as a modal, or if the browser will navigate to the `userProfileUrl` where [`<UserProfile />`][userprofile-ref] is mounted as a page.<br />Defaults to: `"modal"`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/user/user-button.mdx
> +| `afterSignOutUrl` | `string` | The full URL or path to navigate to after a signing out from all accounts (applies to both single-session and multi-session apps) |
```suggestion
| `afterSignOutUrl` | `string` | The full URL or path to navigate to after a signing out from all accounts (applies to both single-session and multi-session apps). |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/user/user-button.mdx
> +| `userProfileProps` | `object` | Specify options for the underlying [`<UserProfile />`][userprofile-ref] component. e.g. `{additionalOAuthScopes: {google: ['foo', 'bar'], github: ['qux']}}` |
```suggestion
| `userProfileProps` | `object` | Specify options for the underlying [`<UserProfile />`][userprofile-ref] component. e.g. `{additionalOAuthScopes: {google: ['foo', 'bar'], github: ['qux']}}`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/components/user/user-profile.mdx
> +| `additionalOAuthScopes` | `object` | Specify additional scopes per OAuth provider that your users would like to provide if not already approved. <br />e.g. `{google: ['foo', 'bar'], github: ['qux']
```suggestion
| `additionalOAuthScopes` | `object` | Specify additional scopes per OAuth provider that your users would like to provide if not already approved. <br />e.g. `{google: ['foo', 'bar'], github: ['qux']}`. |
```

2023-10-03 16:46 UTC, BRKalow commented on docs/references/javascript/clerk/sign-up.mdx
> -| `afterSignUpUrl?` | `string` | The full URL or path to navigate after a successful sign up. |
Good catch!

2023-10-04 17:22 UTC, jescalan approved these changes
LGTM, but note that i didnt go through every page of the preview and check to make sure it looks right, and want to be sure that someone has done so before merge

2023-10-04 20:28 UTC, BRKalow commented on docs/references/javascript/clerk/create-organization.mdx
> +| `routing` | `'hash' \| 'path' \| 'virtual'` | The routing strategy for your pages.<br />Note: If you are using environment variables for Next.js or Remix to specify your routes, this will be set to
I don't think this note is applicable to to this component. AFAIK only sign in and sign up are impacted.

2023-10-04 20:28 UTC, BRKalow commented on docs/references/javascript/clerk/organization-profile.mdx
> +| `routing` | `'hash' \| 'path' \| 'virtual'` | The routing strategy for your pages.<br />Note: If you are using environment variables for Next.js or Remix to specify your routes, this will be set to
I don't think this note is applicable to to this component. AFAIK only sign in and sign up are impacted.

2023-10-04 20:28 UTC, BRKalow commented on docs/references/javascript/clerk/user-profile.mdx
> +| `routing` | `'hash' \| 'path' \| 'virtual'` | The routing strategy for your pages.<br />Note: If you are using environment variables for Next.js or Remix to specify your routes, this will be set to
I don't think this note is applicable to to this component. AFAIK only sign in and sign up are impacted.

2023-10-04 20:55 UTC, BRKalow approved these changes

2023-10-04 20:58 UTC, merged