[WIP] Add Custom Pages for UserProfile and OrganizationProfile docs
clerkinc/clerk-docs pull request #404
Opened 2023-10-09 12:37 UTC by anagstef

This is still work in progress

2023-10-10 19:29 UTC, alexisintech requested changes
I would rename the `organization-profile-custom-pages` file and `user-profile-custom-pages` file to simply be `organization-profile` and `user-profile`
because they already have the `/customization` path in the file name

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +description: How to add custom pages to the `<OrganizationProfile />` component
```suggestion
description: Learn how to add custom pages and include external links within the navigation sidebar of the <OrganizationProfile /> component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +title: Customize Organization Profile
```suggestion
title: <OrganizationProfile /> customization
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +# Custom pages in Organization Profile
```suggestion
# `<OrganizationProfile />`

The `<OrganizationProfile />` component supports the addition of custom pages and use of external links in the navigation sidebar. 
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +To add a custom page, use the `<OrganizationProfile.Page />` component.
```suggestion
Custom pages can be rendered inside the `<OrganizationProfile />` component and provide a way to incorporate app-specific settings or additional functionality.

To add a custom page to the `<OrganizationProfile />` component, use the `<OrganizationProfile.Page />` component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +        `<OrganizationProfile.Page />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` flag.
```suggestion
        `<OrganizationProfile.Page />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +| `url` | `string` | The path segment that will be used to navigate to the custom page. (e.g. if the `OrganizationProfile` component is rendered at `/organization`, then the custom page will be acces
```suggestion
| `url` | `string` | The path segment that will be used to navigate to the custom page. (e.g. if the `OrganizationProfile` component is rendered at `/organization`, then the custom page will be accessed at `/organization/{url}` when using path routing). |
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +In addition to custom pages, you can add external links to the `<OrganizationProfile />` navigation sidebar using the `<OrganizationProfile.Link />` component.
```suggestion
You can add external links to the `<OrganizationProfile />` navigation sidebar using the `<OrganizationProfile.Link />` component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +        `<OrganizationProfile.Link />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` flag.
```suggestion
        `<OrganizationProfile.Link />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +| `url` | `string` | The absolute or relative url to navigate to |
```suggestion
| `url` | `string` | The absolute or relative url to navigate to. |
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +### Reordering Default Routes
```suggestion
### Reordering default routes
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +        `<OrganizationProfile.Page />` and `<OrganizationProfile.Link />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` flag.
```suggestion
        `<OrganizationProfile.Page />` and `<OrganizationProfile.Link />` can be rendered **only on the client**.  For Next.js applications that use App Router, the `"use client";` flag needs to be used.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +- The first item in the list cannot be a `<OrganizationProfile.Link />` component.
```suggestion
It's important to note that the first page in the list will be rendered under the root path `/` (its `url` will be ignored) and the Clerk pages will be rendered under the path `/organitzation-members` and `/organization-settings`. Also, the first item in the list cannot be a `<OrganizationProfile.Link />` component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/organization-profile-custom-pages.mdx
> +        `<OrganizationSwitcher.OrganizationProfilePage />` and `<OrganizationSwitcher.OrganizationProfileLink />` can be rendered **only on the client**, and in Next.js app-router projects, they need
```suggestion
        `<OrganizationSwitcher.OrganizationProfilePage />` and `<OrganizationSwitcher.OrganizationProfileLink />` can be rendered **only on the client**.  For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +title: Customize User Profile
```suggestion
title: <UserProfile /> customization
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +description: How to add custom pages to the `<UserProfile />` component
```suggestion
description: Learn how to add custom pages and include external links within the navigation sidebar of the <UserProfile /> component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +To add a custom page, use the `<UserProfile.Page />` component.
```suggestion
# `<UserProfile />` customization

The `<UserProfile />` component supports the addition of custom pages and use of external links in the navigation sidebar. 

## `<UserProfile.Page />`

Custom pages can be rendered inside the `<UserProfile />` component and provide a way to incorporate app-specific settings or additional functionality.

To add a custom page to the `<UserProfile />` component, use the `<UserProfile.Page />` component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +        `<UserProfile.Page />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` flag.
```suggestion
        `<UserProfile.Page />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +        `<UserProfile.Link />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` flag.
```suggestion
        `<UserProfile.Link />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +        `<UserProfile.Page />` and `<UserProfile.Link />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` flag.
```suggestion
        `<UserProfile.Page />` and `<UserProfile.Link />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +        `<UserButton.UserProfilePage />` and `<UserButton.UserProfileLink />` can be rendered **only on the client**, and in Next.js app-router projects, they need to be under the `"use client";` fla
```suggestion
        `<UserButton.UserProfilePage />` and `<UserButton.UserProfileLink />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +In addition to custom pages, you can add external links to the `<UserProfile />` navigation sidebar using the `<UserProfile.Link />` component.
```suggestion
You can add external links to the `<UserProfile />` navigation sidebar using the `<UserProfile.Link />` component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/components/customization/user-profile-custom-pages.mdx
> +- The first item in the list cannot be a `<UserProfile.Link />` component.
```suggestion
It's important to note that the first page in the list will be rendered under the root path `/` (its `url` will be ignored) and the Clerk pages will be rendered under the path `/account`. Also, the first item in the list cannot be a `<UserProfile.Link />` component.
```

2023-10-10 19:29 UTC, alexisintech commented on docs/manifest.json
> +          ["User Profile", "/components/customization/user-profile-custom-pages"],
```suggestion
          ["<UserProfile />", "/components/customization/user-profile-custom-pages"],
```

2023-10-10 19:29 UTC, alexisintech commented on docs/manifest.json
> +          ["Organization Profile", "/components/customization/organization-profile-custom-pages"]
```suggestion
          ["<OrganizationProfile />", "/components/customization/organization-profile-custom-pages"]
```

2023-10-10 19:29 UTC, alexisintech commented on docs/references/javascript/clerk/organization-profile.mdx
> +Organization profile can be customized by adding custom pages to it. Custom pages are added to the organization profile using the `customPages` prop.
```suggestion
You can add customized pages for the `<OrganizationProfile />` component by using the `customPages` prop.

```

2023-10-12 13:55 UTC, alexisintech approved these changes
great teamwork!!! 😸💖

2023-10-24 00:56 UTC, LekoArts commented on docs/components/customization/organization-profile.mdx
> +    `<OrganizationProfile.Page />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` flag must be added.
```suggestion
    `<OrganizationProfile.Page />` can be rendered **only on the client**. For Next.js applications using App Router, the `"use client";` directive must be added.
```

It's called a directive :) We'll need to adjust that in all the doc

2023-10-24 20:26 UTC, merged