docs: use recommended practices of expo guides -- for EAS
clerkinc/clerk-docs pull request #57
Opened 2023-05-18 16:38 UTC by coelhucas

Changes:

-- | Img
-- | --
Add disclaimer about the needed dependencies that needs to be manually added | ![image](https://github.com/clerkinc/clerk-docs/assets/28108272/5a533d6b-c83a-4b01-ab8c-399c907c772d)
Make instructions more on par with what Next.JS have now | ![image](https://github.com/clerkinc/clerk-docs/assets/28108272/0a77cb3b-be06-43b1-bf31-6e99fe53c19f)

I found the second one specially useful since I worked in many codebases where people would blindly copy the snippets as they were provided.

So now, even if someone copy it and just change the values, they're likely to do as Expo recommends &mdash; and even learn something new about it 🙂

2023-05-18 16:50 UTC, coelhucas commented on src/pages/quickstarts/native/expo.mdx
> +```sh copy filename="app.config.js"
Is it worth to add `eas.json` example as well? Or just redirect to [Environment variables and secrets](https://docs.expo.dev/build-reference/variables/)

2023-05-18 16:59 UTC, coelhucas commented on src/pages/quickstarts/native/expo.mdx
> +```sh copy filename="app.config.js"
Updated to
![image](https://github.com/clerkinc/clerk-docs/assets/28108272/429cbd82-a7ae-4678-8ef2-4c0e778a3594)

2023-05-22 13:09 UTC, perkinsjr commented
Hey there, 

Appreciate the PR here. Going through it now.

Just to let you know the clerk-docs project is actually an ongoing project that isn't public at this time as we work towards production release. Feel free to push more PRs to our open source project. 

Cheers

2023-05-22 13:11 UTC, perkinsjr requested changes
Just need the one change on the file, that I left a comment on.

2023-05-22 13:11 UTC, perkinsjr commented on src/pages/quickstarts/native/expo.mdx
> +<Callout type="warning">
This isn't required to work with Clerk, this is all you need to work with Clerk and OAuth so we can remove this

```
"dependencies": {
    "@clerk/clerk-expo": "^0.17.2",
    "expo": "~48.0.15",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },  ```

2023-05-22 14:15 UTC, merged